#!/bin/sh

# Check if necessary programs are installed
for prog in jq curl nsxiv fzf; do
    if [ ! "$(command -v $prog)" ]; then
	echo "Please install $prog!"
	exit 1
    fi
done

# args
while [ $# -gt 0 ]; do
    case $1 in
	-l|--limit)
	    shift
	    LIMIT=$1
	    case $LIMIT in
		''|*[!0-9]*)
		    echo 'limit is NaN'
		    exit 1
	    esac
	    ;;
	-s|--sort)
	    shift
	    SORT=$1
	    ;;
	*)
	    subreddit=$1
	    ;;
    esac
    shift
done


configdir="${XDG_CONFIG_HOME:-$HOME/.config}/redyt"
configfile="$configdir/subreddit.txt"

[ ! -d "$configdir" ] && mkdir -p "$configdir"

defaultsub="linuxmemes"
[ ! -f "$configfile" ] && echo $defaultsub >> "$configfile"

# If no argument is passed
[ -z "$subreddit" ] && subreddit="$(fzf -i < $configfile)"
[ -z "$subreddit" ] && echo "no sub chosen" && exit 1

if ! rg "^$subreddit\$" $configfile >/dev/null; then
    echo "$subreddit" >> "$configfile"
    subreddits="$(cat "$configfile" | sort -u)"
    echo $subreddits | tr ' ' '\n' > "$configfile"
    unset subreddits
fi

cachedir="/tmp/redyt/$subreddit"
[ ! -d "$cachedir" ] && mkdir -p "$cachedir"


echo "Downloading metadata."
base_url="https://www.reddit.com/r"
curl -s "$base_url/$subreddit/${SORT:-hot}.json?limit=${LIMIT:-100}" \
    -o $cachedir/tmp.json -H "User-agent: 'your bot 0.1'"

[ $? -ne 0 ] && echo "Couldn't fetch data" && exit 1

# Create a list of images
imgs=$(jq '.' < "$cachedir/tmp.json" | rg url_overridden_by_dest \
    | rg -o "http(s|)://.*(jpg|png)\b" | sort -u)

# If there are no images, exit
if [ -z "$imgs" ]; then
    echo "sadly, there are no images for $subreddit"
    exit 1
fi

# Download images to $cachedir
cd "$cachedir"
for img in $imgs; do
	if [ ! -e "$cachedir/${img##*/}" ]; then
		curl -sO $img &
	fi
done

printf "Downloading : $(echo "$imgs" | wc -w ) \n"
count=$(ps aux | rg -e curl -e redd | rg -v rg | wc -l)
while [ 0 -lt $count ]; do
    count=$(ps aux | rg -e curl -e redd | rg -v rg | wc -l)
    printf "\rRemaining : $count "
    sleep 0.25
done
printf "\r👍 Download Finished, Enjoy! 😊\n"

rm "$cachedir/tmp.json"

read -p "Additional flags for nsxiv : " temp

# Display the images
nsxiv -a -s f "$cachedir" $temp

