#!/bin/sh

# Check if necessary programs are installed
for prog in jq imv; do
    if [ ! "$(command -v $prog)" ]; then
	echo "Please install $prog!"
	exit 1
    fi
done

# args
while [ $# -gt 0 ]; do
    case $1 in
	-l|--limit)
	    shift
	    LIMIT=$1
	    case $LIMIT in
		''|*[!0-9]*)
		    echo 'limit is NaN'
		    exit 1
	    esac
	    ;;
	-s|--sort)
	    shift
	    SORT=$1
	    ;;
	*)
	    subreddit=$1
	    ;;
    esac
    shift
done

[ -z "$subreddit" ] && echo "no sub chosen" && exit 1

cachedir="/tmp/redyt/$subreddit"
[ ! -d "$cachedir" ] && mkdir -p "$cachedir"

echo "Downloading metadata."
base_url="https://www.reddit.com/r"
curl -s "$base_url/$subreddit/${SORT:-hot}.json?limit=${LIMIT:-100}" \
    -o $cachedir/tmp.json -H "User-agent: 'your bot 0.1'"

[ $? -ne 0 ] && echo "Couldn't fetch data" && exit 1

# Create a list of images
imgs=$(jq '.' < "$cachedir/tmp.json" | rg url_overridden_by_dest \
    | rg -o "http(s|)://.*(jpg|png)\b" | sort -u)

# If there are no images, exit
if [ -z "$imgs" ]; then
    echo "sadly, there are no images for $subreddit"
    exit 1
fi

# Download images to $cachedir
printf "Downloading : $(echo "$imgs" | wc -w ) \n"

cd "$cachedir"
echo $imgs | tr ' ' '\n' | xargs -I _ -P 5 curl -C - -sO _ &
wait

printf "\rDownload Completed\n"

rm "$cachedir/tmp.json"

hyprctl notify 5 2000 0 " Redyt: Download Finished, Enjoy!" > /dev/null

# Display the images
imv "$cachedir"

